// vue-client/src/App.vue
<script setup>
import { RouterView } from 'vue-router';
import Footer from './components/layout/Footer.vue'
import ProtectedAdminRoute from './components/common/ProtectedAdminRoute.vue';
import ErrorPage from './components/common/ErrorPage.vue';
import './App.css';
</script>
<template>
    <UserProvider>
        <div className="appContainer"> 
          <!--<Header/>-->
          <div className="contentBackground">
            <nav>
    <RouterLink to="/">Go to Home</RouterLink>
    <RouterLink to="/about">Go to About</RouterLink>
    <RouterLink to="/error">Go to Error</RouterLink>
    <RouterLink to="apply">Go to Apply</RouterLink>
    <RouterLink to="/profile">Go to Profile</RouterLink>
    <RouterLink to="/admin">Go to Admin</RouterLink>
  </nav>
          </div> 
          <Footer/>
        </div>
    </UserProvider> 
</template>
<!-- old stuff in this comment 
import Header from './components/layout/Header.vue';  
import Footer from './components/layout/Footer.vue'; 
import ApplicationForm from './components/forms/ApplicationForm.jsx';
import ProfilesForm from './components/forms/ProfilesForm.jsx';
import HomePage from './components/forms/HomePage.jsx';
import AdminForm from './components/forms/AdminForm.jsx';

import 'bootstrap/dist/css/bootstrap.min.css';
import { UserProvider } from './context/UserContext.jsx'; 
//import TicketForwarder from './utils/TicketForwarder.js';



-->

// clientReact/src/App.jsx
import React from 'react';
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
import ApplicationForm from './components/forms/ApplicationForm.jsx';
import ProfilesForm from './components/forms/ProfilesForm.jsx';
import HomePage from './components/forms/HomePage.jsx';
import AdminForm from './components/forms/AdminForm.jsx';
import Header from './components/layout/Header.jsx';  
import Footer from './components/layout/Footer.jsx'; 
import 'bootstrap/dist/css/bootstrap.min.css';
import { UserProvider } from './context/UserContext.jsx'; 
//import TicketForwarder from './utils/TicketForwarder.js';
import ProtectedAdminRoute from './components/common/ProtectedAdminRoute.jsx';
import ErrorPage from './components/common/ErrorPage.jsx';
import './App.css';

function App() {
  return (
    //<UserProvider>
      <Router>
        <div className="appContainer"> 
          <Header/>
          <div className="contentBackground">
            <Routes>
              <Route path="/" element={<HomePage />} />
              <Route path="/Home" element={<HomePage />} />
              <Route path="/Apply" element={<ApplicationForm />} />
              <Route path="/Profile" element={<ProfilesForm />} />
              <Route path="/AdminPage" element={
                <ProtectedAdminRoute>
                  <AdminForm />
                </ProtectedAdminRoute>
              } />
              
              <Route path="*" element={<ErrorPage />} />
            </Routes>
          </div> 
          <Footer/>
        </div>
      </Router>
    //</UserProvider>
  );
}

export default App;
